### ISSUE TITLE
Using send vs pcap_sendpacket

### ISSUE THREAD

**Issue by int3rlop3r** [cmouse/ip-sla-responder#11]
Hi,

I just have a question regarding the code. Could you please tell me why you've used `send` instead of using pcap's `pcap_sendpacket`?

https://github.com/cmouse/ip-sla-responder/blob/3b6695973ce839fda4ac6206372d7364ffab85d6/main.c#L29

**Comment by cmouse** [comment]
Probably no particular reason.

**Comment by int3rlop3r** [comment]
Got it, thanks for the quick response! :+1:
