### ISSUE TITLE
Don`t can compile

### ISSUE THREAD

**Issue by switch0** [cmouse/ip-sla-responder#8]
After command make, i`m get:

[root@localhost ip-sla-responder-release_02]# make
cc -W -Wall -Wno-unused -g -O2 -DCONFIGFILE="\"/etc/responder.conf\"" -c -o utils.o utils.c
In file included from utils.c:1:
responder.h:13:23: error: pcap/pcap.h: No such file or directory
In file included from utils.c:1:
responder.h:112: warning: ‘struct pcap_pkthdr’ declared inside parameter list
utils.c: In function ‘ts_to_ntp’:
utils.c:14: warning: integer constant is too large for ‘unsigned long’ type
make: *** [utils.o] Error 1

Pls help me.

**Comment by eimann** [comment]
Installing libpcap should help.

**Comment by switch0** [comment]
Thanks for your reply,
I already have:
[root@localhost ip-sla-responder-release_02]# yum install libpcap
Loaded plugins: fastestmirror, kmod
Loading mirror speeds from cached hostfile
Setting up Install Process
Package 14:libpcap-1.4.0-1.20130826git2dbcaa1.el6.i686 already installed and latest version
Nothing to do

**Comment by eimann** [comment]
You are missing libpcap headers, it's clear from the output you posted.

**Comment by switch0** [comment]
Big thanks eimann!
"yum install libpcap-devel" resolved this issue.
