### ISSUE TITLE
ip-sla-responder not answer. How diagnose and solve this problem?

### ISSUE THREAD

**Issue by switch0** [cmouse/ip-sla-responder#9]
ip-sla-responder not answer:
R1#show ip sla s 

Round Trip Time (RTT) for       Index 1
        Latest RTT: NoConnection/Busy/Timeout
Latest operation start time: *00:20:11.407 UTC Fri Mar 1 2002
Latest operation return code: Timeout
Number of successes: 0
Number of failures: 13
Operation time to live: Forever

R1 config:
ip sla 1
 udp-echo 192.168.216.129 50505
 frequency 10
ip sla schedule 1 life forever start-time now

responder.conf:
# set to 0 if you do not wish to support dot1q vlans
vlansupport=0

# set for ipv4 support
ipaddress=192.168.216.129

# set for ipv6 support
#ip6address=2001:6e8:280::1:342d

# interface to listen on (defaults to first non-loopback)
iface=eth0

# debug level (0 = nothing, 1 = something, 2 = with packet dumps)
debuglevel=2

# mac address (defaults to interface if nothing given)
#mac=de:ad:be:ef:00:01

# cisco ip sla port range (defaults to 50505)
#ciscoport=50505
#ciscoport=50000:60000

How diagnose and solve this problem?

**Comment by cmouse** [comment]
Can you ping the ip? Is there route or connected interface on upstream device?

**Comment by switch0** [comment]
Yes, i can ping this ip. It is directly connected interface.

**Comment by cmouse** [comment]
Did you configure it on the server? You should not.  The software wants to handle the ip stack itself.

**Comment by cmouse** [comment]
It can also answer to ping so you can test that it works.

**Comment by switch0** [comment]
I changed responder.conf:
ipaddress=192.168.216.132
and config R1:
ipaddress=192.168.216.132

After change I can ping 192.168.216.132 from R1, but SLA not work:

Round Trip Time (RTT) for       Index 1
        Latest RTT: NoConnection/Busy/Timeout
Latest operation start time: *00:33:02.567 UTC Fri Mar 1 2002
Latest operation return code: Timeout
Number of successes: 0
Number of failures: 34
Operation time to live: Forever

I`am got the sniff with traffic between R1 and responder:
![image](https://cloud.githubusercontent.com/assets/12744705/8077329/817a64d8-0f5d-11e5-921a-9f50c302b729.png)
Responder answer to control sla maessage from R1 on port 1967, but not answer to next sla packet on port 50505.

**Comment by cmouse** [comment]
Can you set debuglevel to 2 and put result to gist?

**Comment by switch0** [comment]
https://gist.github.com/switch0/3f7eb990df2ca3a74f56#file-debuglevel2

**Comment by cmouse** [comment]
Thanks I'll have a look at it.

**Comment by cmouse** [comment]
I have written a possible fix for this, can you test it? It's now in master.

Also, for perfomance reasons, I would recommend using IP address for the ip sla responder not assigned to the server at all on any interface. If you have a /29 now, maybe use the next IP?

**Comment by switch0** [comment]
I`m tested, but not work too:(
result debuglevel 2:
https://gist.github.com/switch0/8334719137127f5afb01#file-gistfile1-txt
I use IP address for the ip sla responder not assigned to the server at all on any interface.
Repet test with 192.168.216.133 on responder?

**Comment by switch0** [comment]
I`m changed SLA config R1:
ip sla 1
 udp-jitter 192.168.216.132 50505
ip sla schedule 1 life forever start-time now
And got successe:

Round Trip Time (RTT) for       Index 1
        Latest RTT: 13 milliseconds
Latest operation start time: 14:21:54.333 UTC Wed Jun 10 2015
Latest operation return code: OK
RTT Values:
        Number Of RTT: 10               RTT Min/Avg/Max: 9/13/24 milliseconds
Latency one-way time:
        Number of Latency one-way Samples: 10
        Source to Destination Latency one way Min/Avg/Max: 4/9/22 milliseconds
        Destination to Source Latency one way Min/Avg/Max: 2/4/6 milliseconds
Jitter Time:
        Number of SD Jitter Samples: 9
        Number of DS Jitter Samples: 9
        Source to Destination Jitter Min/Avg/Max: 0/4/18 milliseconds
        Destination to Source Jitter Min/Avg/Max: 0/1/3 milliseconds
Packet Loss Values:
        Loss Source to Destination: 0           Loss Destination to Source: 0
        Out Of Sequence: 0      Tail Drop: 0
        Packet Late Arrival: 0  Packet Skipped: 0
Voice Score Values:
        Calculated Planning Impairment Factor (ICPIF): 0
        Mean Opinion Score (MOS): 0
Number of successes: 2
Number of failures: 0
Operation time to live: Forever

**Comment by cmouse** [comment]
can you run udp echo between two devices and provide pcaps?

**Comment by cmouse** [comment]
Btw, loving those destination to source stats.

**Comment by cmouse** [comment]
@switch0 I think I fixed the UDP echo feature, can you test it again? It's in latest master.

**Comment by switch0** [comment]
Yes, the fix work:

Round Trip Time (RTT) for       Index 1
        Latest RTT: 6 milliseconds
Latest operation start time: 06:20:20.541 UTC Thu Jun 11 2015
Latest operation return code: OK
Number of successes: 1
Number of failures: 0
Operation time to live: Forever

**Comment by cmouse** [comment]
Can I close this issue?

**Comment by switch0** [comment]
Yes, of couse.
Will you do new release?

**Comment by cmouse** [comment]
Soon.
